config/routes.rb
King601::Application.routes.draw do
  root 'pages#home'

  get "contact" => "pages#contact"
  get "server" => "pages#servers"
  get "servers" => "pages#servers"
  get "uhc" => "pages#events"
  get "events" => "pages#events"

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def servers
  end

  def events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
	<div class="well footerwell">
		&copy; 2012-2014 King601.com 
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container"> 
 <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "King601", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Contact Me", contact_path %></li>
        <li><%= link_to "Servers", servers_path %></li>
        <li class="dropdown">
         
          <%= link_to raw("Events" +(" <b class= 'caret'></b>")), events_path, :class => "dropdown-toggle", :data => {:toggle=>"dropdown"}  %>
          <ul class="dropdown-menu">
            <li role="presentation" class="dropdown-header">UltraHardcore</li>
            <li><a href="#">Information</a></li>
            <li><a href="#">Video Archives</a></li>
            <li><a href="#">Livestream View</a></li>
            <li class="divider"></li>
            <li role="presentation" class="dropdown-header">Community Days</li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
          <li><%= link_to "AthensMC Forums", "http://forums.athensmc.com" %></li>

        <li><%= link_to "My Blog", 'http://blog.king601.com' %></li>

    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- End Container to help pull in navbar content-->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= @pg_title %> / King601.com</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>

	</head>

	<body>

		<%= render 'layouts/header' %>

		<div class="container">
				<%= yield %>
		</div>

		<%= render 'layouts/footer' %>
	  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

	</body>

</html>

app/views/pages/contact.html.erb
<% @pg_title="Contact Me" %>

<div class="well">
	<div class="page-header">
		<h1>Contact Me</h1>
	</div>
	<p>
		Greetings! I'm estatic that you found my website in the first place, let alone the fact that you'd like to reach out and get a hold of me. Here's where you'll be most likely to reach me...
	</p>
</div>

app/views/pages/events.html.erb
<% @pg_title="Events" %>

<div class="well">
	<div class="page-header">
		<h1>Events Page</h1>
	</div>
	<p>
		Events Page!
	</p>
</div>

app/views/pages/home.html.erb
<% @pg_title="Home" %>

<div class="well">
	<div class="page-header">
		<h1>Welcome!</h1>
	</div>
	<div class="Well">
		<div class="col-md-6">
			<p>Hello visitor from the internet! My name is King601 and I am a gamer. I make YouTube videos for fun and I run Minecraft Servers. I like to try my hand at just about anything that looks fun and sometimes I get fustrated with things and just forget about 'em.</p>

			<p>I finally <del>got around to making</del> made myself build my website on Ruby on Rails so please check it out and <%= link_to "Contact Me", contact_path %> if you have a question.</p>
		</div>
		<div class="col-md-6">

				<a class="twitter-timeline" data-dnt="true" href="https://twitter.com/king601" data-widget-id="408078926028623872">Tweets by @king601</a>
				

		</div>
		&nbsp
	</div>

		Progress towards my new website
		<div class="progress">
		  <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100" style="width: 15%">
		    <span class="sr-only">15% Complete (warning)</span>
		  </div>
		</div>
</div>

app/views/pages/servers.html.erb
<% @pg_title="My Server" %>

<div class="well">
	<div class="page-header">
		<h1>Come play with me!</h1>
	</div>
	<p>
		Servers Page
	</p>
</div>